### ISSUE TITLE
Feature Request: Create a firefox extension?

### ISSUE THREAD

**Issue by devjones** [marcus-crane/comments-to-readwise#7]
This is the extension I've been looking for!  Any possibility you can create a firefox add-on as well?  I just switched to Chrome just to use this, but I'd much prefer to use firefox.

**Comment by marcus-crane** [comment]
Hi there,

It's a bit hacked together so I'll need to set up a proper deployment pipeline but I've put together a Firefox version. It successfully uploads Hacker News comments and should work with other supported sites although I haven't tested it end to end.

I've submitted it to the Firefox Addon Store where it should be available at https://addons.mozilla.org/en-US/firefox/addon/comments-to-readwise/ once reviewed but that will probably take a few days.

In the meantime, you can manually install it by following the instructions here: https://github.com/marcus-crane/comments-to-readwise#firefox-users

**Comment by marcus-crane** [comment]
As a bit more background, Firefox is in a bit of an awkward transition period when it comes to browser extensions.

Chrome is about to remove Manifest V2 (this extension uses V3) while Firefox won't actually have support for it until [January 17, 2023](https://blog.mozilla.org/addons/2022/11/17/manifest-v3-signing-available-november-21-on-firefox-nightly/). If V3 was there earlier, I could have submitted a Firefox version earlier without any changes required.

Once Firefox has V3 support next year, it should be able to load this extension as is without any of the manual changes that I did, and would have to do every time a new version is released.

To be clear though, I don't fault Firefox for any of this. V3 has some changes that... aren't great but Google Chrome is opting them as the new standard which gives them a lot of weight.

**Comment by devjones** [comment]
Sweet! Thanks for the quick turnaround.

**Comment by marcus-crane** [comment]
Hey there,

Apparently I missed it but the extension was approved so you can install it from the Firefox Addon Store here: https://addons.mozilla.org/en-US/firefox/addon/comments-to-readwise/
